#!/usr/bin/env python3
"""
Interactive Mask Editor for SAM2 AMG Output

This script provides an interactive GUI to edit masks generated by sam2_amg_inference.py.
Users can:
- Delete individual masks
- Combine/merge multiple masks
- Edit existing masks by resizing their bounding boxes
- Create new masks by drawing bounding boxes
- Undo/redo operations
- Save modifications back to the original JSON file

The edited masks are saved in-place and can be used for downstream processing
like interactive classification.

Usage:
    python interactive_mask_editor.py --results_json /path/to/results.json
"""

import sys
import os
import argparse
import numpy as np
import cv2
import json
from pathlib import Path
from typing import Dict, Any, List, Tuple, Optional
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2Tk
from matplotlib.figure import Figure
import tkinter as tk
from tkinter import ttk, messagebox, filedialog
from PIL import Image, ImageTk


class MaskEditor:
    """Interactive mask editor with GUI"""

    def __init__(self, results_json_path: str):
        """
        Initialize the mask editor

        Args:
            results_json_path: Path to the results JSON file
        """
        self.results_json_path = results_json_path

        # Load JSON first to get paths to other files
        self._load_json()

        # Derive other file paths from JSON and directory structure
        self._derive_file_paths()

        # Load data
        self._load_image()
        self._load_masks()

        # State management
        self.selected_masks = set()  # Indices of selected masks for combining
        self.history = []  # For undo functionality
        self.redo_stack = []  # For redo functionality
        self.current_overlay = None
        self.modified = False  # Track if changes have been made

        # UI state
        self.show_labels = True
        self.alpha = 0.5  # Transparency for overlay
        self.highlight_alpha = 0.8  # Transparency for selected masks

        # Edit mode state
        self.edit_mode = None  # None, 'edit', or 'create'
        self.editing_mask_idx = None  # Index of mask being edited
        self.editing_bbox = None  # Current bounding box being edited [x1, y1, x2, y2]
        self.drag_handle = None  # Which handle is being dragged ('tl', 'tr', 'bl', 'br', 'edge', None)
        self.drag_start = None  # Starting position for drag
        self.creating_bbox = None  # Bounding box being created [x1, y1, x2, y2]
        self.create_start = None  # Starting point for new mask creation

        # Colors for visualization
        np.random.seed(42)
        self.colors = self._generate_colors(len(self.masks))

        # Initialize GUI
        self._setup_gui()

    def _load_image(self):
        """Load the original image"""
        if not os.path.exists(self.image_path):
            raise FileNotFoundError(f"Image not found: {self.image_path}")

        self.image = cv2.imread(self.image_path)
        if self.image is None:
            raise ValueError(f"Could not load image: {self.image_path}")

        # Convert BGR to RGB for display
        self.image_rgb = cv2.cvtColor(self.image, cv2.COLOR_BGR2RGB)
        print(f"Loaded image: {self.image_path}")
        print(f"Image shape: {self.image.shape}")

    def _load_masks(self):
        """Load masks from .npz file or create from bboxes in JSON"""
        if os.path.exists(self.masks_npz_path):
            # Load actual masks from .npz file
            data = np.load(self.masks_npz_path)
            self.masks = list(data['masks'])  # Convert to list for easier manipulation
            self.scores = list(data['scores'])
            self.use_bbox_masks = False
            print(f"Loaded {len(self.masks)} masks from: {self.masks_npz_path}")
        else:
            # Fallback: Create rectangular masks from bboxes in JSON
            print(f"Warning: .npz file not found at {self.masks_npz_path}")
            print("Creating rectangular masks from bounding boxes in JSON...")

            masks_info = self.json_data.get('masks_info', [])
            if not masks_info:
                raise ValueError("No masks_info found in JSON file")

            # Get image dimensions
            h, w = self.image.shape[:2]

            self.masks = []
            self.scores = []

            for mask_info in masks_info:
                # Create binary mask from bbox
                bbox = mask_info['bbox']  # [x1, y1, x2, y2]
                mask = np.zeros((h, w), dtype=bool)
                mask[bbox[1]:bbox[3], bbox[0]:bbox[2]] = True

                self.masks.append(mask)
                self.scores.append(mask_info['score'])

            self.use_bbox_masks = True
            print(f"Created {len(self.masks)} rectangular masks from JSON bounding boxes")
            print("Note: These are approximate rectangular masks, not the original segmentation masks")

    def _load_json(self):
        """Load results JSON file"""
        if not os.path.exists(self.results_json_path):
            raise FileNotFoundError(f"JSON file not found: {self.results_json_path}")

        with open(self.results_json_path, 'r') as f:
            self.json_data = json.load(f)

        print(f"Loaded JSON metadata from: {self.results_json_path}")
        print(f"JSON contains {len(self.json_data.get('masks_info', []))} masks")

    def _derive_file_paths(self):
        """Derive image and masks paths from JSON and directory structure"""
        json_path = Path(self.results_json_path)
        json_dir = json_path.parent

        # Get image path from JSON
        if 'image_path' in self.json_data:
            self.image_path = self.json_data['image_path']
            # If it's a relative path or doesn't exist, try to find it
            if not os.path.exists(self.image_path):
                # Try relative to JSON directory
                image_name = Path(self.image_path).name
                potential_path = json_dir / image_name
                if potential_path.exists():
                    self.image_path = str(potential_path)
                else:
                    print(f"WARNING: Image path from JSON not found: {self.image_path}")
        else:
            raise ValueError("JSON file does not contain 'image_path' field")

        # Derive masks .npz path from JSON filename
        # JSON format: {image_name}_results.json
        # Masks format: {image_name}_masks.npz
        json_stem = json_path.stem
        if json_stem.endswith('_results'):
            masks_stem = json_stem.replace('_results', '_masks')
        else:
            # Fallback: just append _masks
            masks_stem = json_stem + '_masks'

        self.masks_npz_path = str(json_dir / f"{masks_stem}.npz")

        print(f"Derived masks path: {self.masks_npz_path}")
        print(f"Derived image path: {self.image_path}")

        # Note: We don't error here if .npz doesn't exist - _load_masks will handle it

    def _generate_colors(self, n: int) -> np.ndarray:
        """Generate distinct colors for masks"""
        if n <= 20:
            colors = plt.cm.tab20(np.linspace(0, 1, 20))[:n, :3]
        else:
            np.random.seed(42)
            colors = np.random.rand(n, 3)
        return colors

    def _setup_gui(self):
        """Setup the GUI interface"""
        self.root = tk.Tk()
        self.root.title("Interactive Mask Editor")
        self.root.geometry("1400x900")

        # Create main layout
        self._create_menu_bar()
        self._create_toolbar()
        self._create_main_layout()
        self._create_status_bar()

        # Initial render
        self.render_visualization()

        # Bind keyboard shortcuts
        self.root.bind('<Control-z>', lambda e: self.undo())
        self.root.bind('<Control-y>', lambda e: self.redo())
        self.root.bind('<Control-s>', lambda e: self.save())
        self.root.bind('<Delete>', lambda e: self.delete_selected_masks())
        self.root.bind('<Escape>', lambda e: self.exit_edit_mode() if self.edit_mode else self.clear_selection())
        self.root.bind('e', lambda e: self.enter_edit_mode())
        self.root.bind('n', lambda e: self.enter_create_mode())
        self.root.bind('<Return>', lambda e: self.apply_edit() if self.edit_mode else None)

    def _create_menu_bar(self):
        """Create menu bar"""
        menubar = tk.Menu(self.root)
        self.root.config(menu=menubar)

        # File menu
        file_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="File", menu=file_menu)
        file_menu.add_command(label="Save", command=self.save, accelerator="Ctrl+S")
        file_menu.add_command(label="Save As...", command=self.save_as)
        file_menu.add_separator()
        file_menu.add_command(label="Exit", command=self.on_closing)

        # Edit menu
        edit_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="Edit", menu=edit_menu)
        edit_menu.add_command(label="Undo", command=self.undo, accelerator="Ctrl+Z")
        edit_menu.add_command(label="Redo", command=self.redo, accelerator="Ctrl+Y")
        edit_menu.add_separator()
        edit_menu.add_command(label="Edit Selected Mask", command=self.enter_edit_mode, accelerator="E")
        edit_menu.add_command(label="Create New Mask", command=self.enter_create_mode, accelerator="N")
        edit_menu.add_separator()
        edit_menu.add_command(label="Delete Selected", command=self.delete_selected_masks, accelerator="Del")
        edit_menu.add_command(label="Combine Selected", command=self.combine_selected_masks)
        edit_menu.add_command(label="Clear Selection", command=self.clear_selection, accelerator="Esc")

        # View menu
        view_menu = tk.Menu(menubar, tearoff=0)
        menubar.add_cascade(label="View", menu=view_menu)
        view_menu.add_command(label="Toggle Labels", command=self.toggle_labels)
        view_menu.add_command(label="Increase Transparency", command=lambda: self.adjust_alpha(0.1))
        view_menu.add_command(label="Decrease Transparency", command=lambda: self.adjust_alpha(-0.1))

    def _create_toolbar(self):
        """Create toolbar with action buttons"""
        toolbar = ttk.Frame(self.root)
        toolbar.pack(side=tk.TOP, fill=tk.X, padx=5, pady=5)

        # Edit/Create buttons
        ttk.Button(toolbar, text="Edit Mask (E)", command=self.enter_edit_mode).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Create New (N)", command=self.enter_create_mode).pack(side=tk.LEFT, padx=2)

        ttk.Separator(toolbar, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=10)

        # Action buttons
        ttk.Button(toolbar, text="Delete Selected", command=self.delete_selected_masks).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Combine Selected", command=self.combine_selected_masks).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Clear Selection", command=self.clear_selection).pack(side=tk.LEFT, padx=2)

        ttk.Separator(toolbar, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=10)

        ttk.Button(toolbar, text="Undo", command=self.undo).pack(side=tk.LEFT, padx=2)
        ttk.Button(toolbar, text="Redo", command=self.redo).pack(side=tk.LEFT, padx=2)

        ttk.Separator(toolbar, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=10)

        ttk.Button(toolbar, text="Save", command=self.save).pack(side=tk.LEFT, padx=2)

        ttk.Separator(toolbar, orient=tk.VERTICAL).pack(side=tk.LEFT, fill=tk.Y, padx=10)

        # Toggle labels
        self.show_labels_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(toolbar, text="Show Labels", command=self.toggle_labels,
                       variable=self.show_labels_var).pack(side=tk.LEFT, padx=2)

        # Alpha slider
        ttk.Label(toolbar, text="Opacity:").pack(side=tk.LEFT, padx=(10, 2))
        self.alpha_var = tk.DoubleVar(value=self.alpha)
        alpha_slider = ttk.Scale(toolbar, from_=0.0, to=1.0, orient=tk.HORIZONTAL,
                                length=100, variable=self.alpha_var,
                                command=self.on_alpha_change)
        alpha_slider.pack(side=tk.LEFT, padx=2)

    def _create_main_layout(self):
        """Create main layout with canvas and mask list"""
        main_frame = ttk.Frame(self.root)
        main_frame.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

        # Left side: Canvas
        canvas_frame = ttk.Frame(main_frame)
        canvas_frame.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)

        # Create matplotlib figure
        self.fig = Figure(figsize=(10, 8))
        self.ax = self.fig.add_subplot(111)
        self.canvas = FigureCanvasTkAgg(self.fig, master=canvas_frame)
        self.canvas.get_tk_widget().pack(fill=tk.BOTH, expand=True)

        # Add matplotlib toolbar
        toolbar_frame = ttk.Frame(canvas_frame)
        toolbar_frame.pack(fill=tk.X)
        NavigationToolbar2Tk(self.canvas, toolbar_frame)

        # Connect mouse events
        self.fig.canvas.mpl_connect('button_press_event', self.on_canvas_click)
        self.fig.canvas.mpl_connect('button_release_event', self.on_canvas_release)
        self.fig.canvas.mpl_connect('motion_notify_event', self.on_canvas_motion)

        # Right side: Mask list
        right_frame = ttk.Frame(main_frame, width=300)
        right_frame.pack(side=tk.RIGHT, fill=tk.BOTH, padx=(5, 0))
        right_frame.pack_propagate(False)

        # Mask list label
        ttk.Label(right_frame, text="Masks List", font=('Arial', 12, 'bold')).pack(pady=5)

        # Info label
        self.info_label = ttk.Label(right_frame, text=f"Total: {len(self.masks)} masks")
        self.info_label.pack(pady=2)

        # Search/filter frame
        filter_frame = ttk.Frame(right_frame)
        filter_frame.pack(fill=tk.X, padx=5, pady=5)
        ttk.Label(filter_frame, text="Filter:").pack(side=tk.LEFT)
        self.filter_var = tk.StringVar()
        self.filter_var.trace_add('write', lambda *args: self.update_mask_list())
        filter_entry = ttk.Entry(filter_frame, textvariable=self.filter_var)
        filter_entry.pack(side=tk.LEFT, fill=tk.X, expand=True, padx=5)

        # Scrollable mask list
        list_frame = ttk.Frame(right_frame)
        list_frame.pack(fill=tk.BOTH, expand=True, padx=5, pady=5)

        scrollbar = ttk.Scrollbar(list_frame)
        scrollbar.pack(side=tk.RIGHT, fill=tk.Y)

        self.mask_listbox = tk.Listbox(list_frame, yscrollcommand=scrollbar.set,
                                       selectmode=tk.EXTENDED, font=('Courier', 9))
        self.mask_listbox.pack(side=tk.LEFT, fill=tk.BOTH, expand=True)
        scrollbar.config(command=self.mask_listbox.yview)

        # Bind selection event
        self.mask_listbox.bind('<<ListboxSelect>>', self.on_list_selection)

        # Populate mask list
        self.update_mask_list()

        # Details panel
        details_frame = ttk.LabelFrame(right_frame, text="Selection Details", padding=5)
        details_frame.pack(fill=tk.X, padx=5, pady=5)

        self.details_text = tk.Text(details_frame, height=6, wrap=tk.WORD, font=('Courier', 9))
        self.details_text.pack(fill=tk.BOTH, expand=True)
        self.update_details_panel()

    def _create_status_bar(self):
        """Create status bar"""
        self.status_bar = ttk.Label(self.root, text="Ready", relief=tk.SUNKEN, anchor=tk.W)
        self.status_bar.pack(side=tk.BOTTOM, fill=tk.X)

    def update_mask_list(self, *args):
        """Update the mask list display"""
        self.mask_listbox.delete(0, tk.END)

        filter_text = self.filter_var.get().lower()

        for i, (mask, score) in enumerate(zip(self.masks, self.scores)):
            area = np.sum(mask)
            mask_text = f"#{i:3d} | Score: {score:.3f} | Area: {area:5d}px"

            # Apply filter
            if filter_text and filter_text not in mask_text.lower():
                continue

            self.mask_listbox.insert(tk.END, mask_text)

            # Highlight selected masks
            if i in self.selected_masks:
                self.mask_listbox.itemconfig(tk.END, bg='lightblue')

        # Update info label
        self.info_label.config(text=f"Total: {len(self.masks)} masks | Selected: {len(self.selected_masks)}")

    def update_details_panel(self):
        """Update the details panel with selection info"""
        self.details_text.delete(1.0, tk.END)

        if not self.selected_masks:
            self.details_text.insert(tk.END, "No masks selected.\n\n")
            self.details_text.insert(tk.END, "Click on masks in the image\n")
            self.details_text.insert(tk.END, "or select from the list.")
        else:
            self.details_text.insert(tk.END, f"Selected: {len(self.selected_masks)} masks\n\n")

            if len(self.selected_masks) == 1:
                idx = list(self.selected_masks)[0]
                mask = self.masks[idx]
                score = self.scores[idx]
                area = np.sum(mask)
                bbox = self._get_mask_bbox(mask)

                self.details_text.insert(tk.END, f"Mask #{idx}\n")
                self.details_text.insert(tk.END, f"Score: {score:.4f}\n")
                self.details_text.insert(tk.END, f"Area: {area} pixels\n")
                self.details_text.insert(tk.END, f"BBox: {bbox[2]-bbox[0]}x{bbox[3]-bbox[1]}\n")
            else:
                total_area = sum(np.sum(self.masks[i]) for i in self.selected_masks)
                avg_score = sum(self.scores[i] for i in self.selected_masks) / len(self.selected_masks)

                self.details_text.insert(tk.END, f"Indices: {sorted(self.selected_masks)}\n")
                self.details_text.insert(tk.END, f"Avg Score: {avg_score:.4f}\n")
                self.details_text.insert(tk.END, f"Total Area: {total_area} px\n")

    def render_visualization(self):
        """Render the current visualization"""
        self.ax.clear()

        # Show original image
        self.ax.imshow(self.image_rgb)

        # Create overlay
        overlay = self.image_rgb.copy().astype(np.float32)

        # Render all masks with semi-transparency
        for i, mask in enumerate(self.masks):
            color = self.colors[i % len(self.colors)] * 255
            alpha = self.highlight_alpha if i in self.selected_masks else self.alpha
            overlay[mask] = (1 - alpha) * overlay[mask] + alpha * color

        self.ax.imshow(overlay.astype(np.uint8), alpha=1.0)

        # Add labels if enabled
        if self.show_labels:
            for i, mask in enumerate(self.masks):
                bbox = self._get_mask_bbox(mask)
                cx = (bbox[0] + bbox[2]) // 2
                cy = (bbox[1] + bbox[3]) // 2

                # Highlight selected masks
                if i in self.selected_masks:
                    self.ax.text(cx, cy, str(i), color='yellow', fontsize=10,
                               fontweight='bold', ha='center', va='center',
                               bbox=dict(boxstyle='round,pad=0.3', facecolor='red', alpha=0.7))
                else:
                    self.ax.text(cx, cy, str(i), color='white', fontsize=8,
                               ha='center', va='center',
                               bbox=dict(boxstyle='round,pad=0.2', facecolor='black', alpha=0.5))

        # Draw editing/creating rectangle
        if self.edit_mode == 'edit' and self.editing_bbox is not None:
            self._draw_edit_bbox(self.editing_bbox)
        elif self.edit_mode == 'create' and self.creating_bbox is not None:
            self._draw_create_bbox(self.creating_bbox)

        self.ax.axis('off')
        title = f'Mask Editor - {len(self.masks)} masks ({len(self.selected_masks)} selected)'
        if self.edit_mode == 'edit':
            title += ' [EDIT MODE - Drag handles to resize, Enter to apply, Esc to cancel]'
        elif self.edit_mode == 'create':
            title += ' [CREATE MODE - Click and drag to draw new mask, Enter to apply, Esc to cancel]'
        self.ax.set_title(title, fontsize=10)
        self.canvas.draw()

    def _draw_edit_bbox(self, bbox):
        """Draw editable bounding box with resize handles"""
        x1, y1, x2, y2 = bbox

        # Draw main rectangle
        from matplotlib.patches import Rectangle
        rect = Rectangle((x1, y1), x2-x1, y2-y1,
                        linewidth=3, edgecolor='cyan', facecolor='none', linestyle='--')
        self.ax.add_patch(rect)

        # Draw corner handles
        handle_size = max(10, min(20, (x2-x1) * 0.05))
        corners = [
            (x1, y1, 'tl'),
            (x2, y1, 'tr'),
            (x1, y2, 'bl'),
            (x2, y2, 'br')
        ]

        for x, y, label in corners:
            self.ax.plot(x, y, 'o', color='cyan', markersize=handle_size,
                        markeredgecolor='white', markeredgewidth=2)

    def _draw_create_bbox(self, bbox):
        """Draw creating bounding box"""
        x1, y1, x2, y2 = bbox

        # Draw rectangle
        from matplotlib.patches import Rectangle
        rect = Rectangle((x1, y1), x2-x1, y2-y1,
                        linewidth=2, edgecolor='lime', facecolor='lime', alpha=0.3, linestyle='-')
        self.ax.add_patch(rect)

        # Show dimensions
        width = x2 - x1
        height = y2 - y1
        cx = (x1 + x2) / 2
        cy = (y1 + y2) / 2
        self.ax.text(cx, cy, f'{width}x{height}', color='white', fontsize=10,
                   ha='center', va='center', fontweight='bold',
                   bbox=dict(boxstyle='round,pad=0.5', facecolor='green', alpha=0.8))

    def on_canvas_click(self, event):
        """Handle canvas click events"""
        if event.inaxes != self.ax:
            return

        x, y = int(event.xdata), int(event.ydata)

        # Check if click is within image bounds
        if x < 0 or x >= self.image.shape[1] or y < 0 or y >= self.image.shape[0]:
            return

        # Handle different modes
        if self.edit_mode == 'edit' and self.editing_bbox is not None:
            # Check if clicking on a handle to start dragging
            self.drag_handle = self._get_handle_at_position(x, y, self.editing_bbox)
            if self.drag_handle:
                self.drag_start = (x, y)
                return

        elif self.edit_mode == 'create':
            # Start creating a new mask
            self.create_start = (x, y)
            self.creating_bbox = [x, y, x, y]
            return

        # Default behavior: select mask
        # Find which mask was clicked (check from top to bottom)
        clicked_mask_idx = None
        for i in range(len(self.masks) - 1, -1, -1):
            if self.masks[i][y, x]:
                clicked_mask_idx = i
                break

        if clicked_mask_idx is not None:
            # Toggle selection
            if clicked_mask_idx in self.selected_masks:
                self.selected_masks.remove(clicked_mask_idx)
            else:
                self.selected_masks.add(clicked_mask_idx)

            self.update_mask_list()
            self.update_details_panel()
            self.render_visualization()
            self.update_status(f"Mask #{clicked_mask_idx} {'selected' if clicked_mask_idx in self.selected_masks else 'deselected'}")

    def on_canvas_release(self, event):
        """Handle mouse button release"""
        if self.edit_mode == 'edit':
            self.drag_handle = None
            self.drag_start = None
        elif self.edit_mode == 'create':
            if self.creating_bbox is not None:
                # Finalize bbox (normalize coordinates)
                x1, y1, x2, y2 = self.creating_bbox
                self.creating_bbox = [min(x1, x2), min(y1, y2), max(x1, x2), max(y1, y2)]
                self.render_visualization()

    def on_canvas_motion(self, event):
        """Handle mouse motion"""
        if event.inaxes != self.ax:
            return

        x, y = int(event.xdata), int(event.ydata)

        # Check bounds
        if x < 0 or x >= self.image.shape[1] or y < 0 or y >= self.image.shape[0]:
            return

        # Handle dragging in edit mode
        if self.edit_mode == 'edit' and self.drag_handle and self.drag_start:
            x1, y1, x2, y2 = self.editing_bbox

            # Update bbox based on which handle is being dragged
            if self.drag_handle == 'tl':
                x1 = min(x, x2 - 10)
                y1 = min(y, y2 - 10)
            elif self.drag_handle == 'tr':
                x2 = max(x, x1 + 10)
                y1 = min(y, y2 - 10)
            elif self.drag_handle == 'bl':
                x1 = min(x, x2 - 10)
                y2 = max(y, y1 + 10)
            elif self.drag_handle == 'br':
                x2 = max(x, x1 + 10)
                y2 = max(y, y1 + 10)

            # Clamp to image bounds
            x1 = max(0, min(x1, self.image.shape[1] - 1))
            y1 = max(0, min(y1, self.image.shape[0] - 1))
            x2 = max(0, min(x2, self.image.shape[1]))
            y2 = max(0, min(y2, self.image.shape[0]))

            self.editing_bbox = [x1, y1, x2, y2]
            self.drag_start = (x, y)
            self.render_visualization()

        # Handle dragging in create mode
        elif self.edit_mode == 'create' and self.create_start:
            self.creating_bbox = [self.create_start[0], self.create_start[1], x, y]
            self.render_visualization()

    def _get_handle_at_position(self, x, y, bbox):
        """Check if position is near a handle"""
        x1, y1, x2, y2 = bbox
        handle_size = max(15, min(25, (x2-x1) * 0.08))

        corners = [
            (x1, y1, 'tl'),
            (x2, y1, 'tr'),
            (x1, y2, 'bl'),
            (x2, y2, 'br')
        ]

        for cx, cy, label in corners:
            if abs(x - cx) <= handle_size and abs(y - cy) <= handle_size:
                return label

        return None

    def on_list_selection(self, event):
        """Handle list selection events"""
        selected_indices = self.mask_listbox.curselection()

        # Map listbox indices back to mask indices (accounting for filtering)
        self.selected_masks.clear()
        for idx in selected_indices:
            mask_text = self.mask_listbox.get(idx)
            # Extract mask index from text (format: "#  i | ...")
            mask_idx = int(mask_text.split('|')[0].strip().replace('#', ''))
            self.selected_masks.add(mask_idx)

        self.update_details_panel()
        self.render_visualization()

    def on_alpha_change(self, value):
        """Handle alpha slider change"""
        self.alpha = float(value)
        self.render_visualization()

    def toggle_labels(self):
        """Toggle mask labels on/off"""
        self.show_labels = self.show_labels_var.get()
        self.render_visualization()

    def adjust_alpha(self, delta: float):
        """Adjust transparency"""
        self.alpha = max(0.0, min(1.0, self.alpha + delta))
        self.alpha_var.set(self.alpha)
        self.render_visualization()

    def clear_selection(self):
        """Clear all selected masks"""
        self.selected_masks.clear()
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status("Selection cleared")

    def enter_edit_mode(self):
        """Enter edit mode to resize selected mask"""
        if len(self.selected_masks) != 1:
            messagebox.showwarning("Invalid Selection",
                                  "Please select exactly one mask to edit.")
            return

        mask_idx = list(self.selected_masks)[0]
        mask = self.masks[mask_idx]

        # Get current bounding box
        bbox = self._get_mask_bbox(mask)

        # Enter edit mode
        self.edit_mode = 'edit'
        self.editing_mask_idx = mask_idx
        self.editing_bbox = list(bbox)  # [x1, y1, x2, y2]

        self.render_visualization()
        self.update_status(f"Editing mask #{mask_idx} - Drag corner handles to resize, Enter to apply, Esc to cancel")

    def enter_create_mode(self):
        """Enter create mode to draw a new mask"""
        self.edit_mode = 'create'
        self.creating_bbox = None
        self.create_start = None

        self.render_visualization()
        self.update_status("Create mode - Click and drag to draw new mask bounding box, Enter to apply, Esc to cancel")

    def exit_edit_mode(self):
        """Exit edit/create mode without applying changes"""
        if self.edit_mode:
            self.edit_mode = None
            self.editing_mask_idx = None
            self.editing_bbox = None
            self.creating_bbox = None
            self.create_start = None
            self.drag_handle = None
            self.drag_start = None

            self.render_visualization()
            self.update_status("Edit/create cancelled")

    def apply_edit(self):
        """Apply current edit or creation"""
        if self.edit_mode == 'edit':
            self._apply_mask_edit()
        elif self.edit_mode == 'create':
            self._apply_mask_creation()

    def _apply_mask_edit(self):
        """Apply mask editing (resize via bounding box)"""
        if self.editing_mask_idx is None or self.editing_bbox is None:
            return

        # Save state for undo
        self._save_state()

        # Get the new bounding box
        x1, y1, x2, y2 = [int(v) for v in self.editing_bbox]

        # Clamp to image bounds
        h, w = self.image.shape[:2]
        x1 = max(0, min(x1, w - 1))
        y1 = max(0, min(y1, h - 1))
        x2 = max(x1 + 1, min(x2, w))
        y2 = max(y1 + 1, min(y2, h))

        # Create new mask from bounding box
        new_mask = np.zeros((h, w), dtype=bool)
        new_mask[y1:y2, x1:x2] = True

        # Update the mask
        self.masks[self.editing_mask_idx] = new_mask

        # Mark as modified
        self.modified = True

        # Exit edit mode
        self.exit_edit_mode()

        # Update UI
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status(f"Mask #{self.editing_mask_idx} resized to {x2-x1}x{y2-y1}")

        # Clear the idx after using it
        self.editing_mask_idx = None

    def _apply_mask_creation(self):
        """Apply mask creation (create new mask from bounding box)"""
        if self.creating_bbox is None:
            messagebox.showwarning("No Mask Drawn",
                                  "Please draw a bounding box for the new mask.")
            return

        # Normalize and validate bbox
        x1, y1, x2, y2 = self.creating_bbox
        x1, x2 = min(x1, x2), max(x1, x2)
        y1, y2 = min(y1, y2), max(y1, y2)

        # Check minimum size
        if (x2 - x1) < 5 or (y2 - y1) < 5:
            messagebox.showwarning("Mask Too Small",
                                  "The mask is too small. Please draw a larger area.")
            return

        # Save state for undo
        self._save_state()

        # Clamp to image bounds
        h, w = self.image.shape[:2]
        x1 = max(0, min(int(x1), w - 1))
        y1 = max(0, min(int(y1), h - 1))
        x2 = max(x1 + 1, min(int(x2), w))
        y2 = max(y1 + 1, min(int(y2), h))

        # Create new mask
        new_mask = np.zeros((h, w), dtype=bool)
        new_mask[y1:y2, x1:x2] = True

        # Add to masks list
        self.masks.append(new_mask)
        self.scores.append(1.0)  # Default score for manually created masks

        # Update colors
        self.colors = self._generate_colors(len(self.masks))

        # Mark as modified
        self.modified = True

        new_mask_idx = len(self.masks) - 1

        # Exit create mode
        self.exit_edit_mode()

        # Select the new mask
        self.selected_masks.clear()
        self.selected_masks.add(new_mask_idx)

        # Update UI
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status(f"Created new mask #{new_mask_idx} with size {x2-x1}x{y2-y1}")

    def delete_selected_masks(self):
        """Delete selected masks"""
        if not self.selected_masks:
            messagebox.showwarning("No Selection", "Please select masks to delete.")
            return

        # Confirm deletion
        result = messagebox.askyesno("Confirm Deletion",
                                     f"Delete {len(self.selected_masks)} selected mask(s)?")
        if not result:
            return

        # Save state for undo
        self._save_state()

        # Sort indices in descending order to delete from end
        sorted_indices = sorted(self.selected_masks, reverse=True)

        # Delete masks
        for idx in sorted_indices:
            del self.masks[idx]
            del self.scores[idx]

        # Update colors
        self.colors = self._generate_colors(len(self.masks))

        # Clear selection
        self.selected_masks.clear()

        # Update UI
        self.modified = True
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status(f"Deleted {len(sorted_indices)} mask(s)")

    def combine_selected_masks(self):
        """Combine selected masks into one"""
        if len(self.selected_masks) < 2:
            messagebox.showwarning("Insufficient Selection",
                                  "Please select at least 2 masks to combine.")
            return

        # Save state for undo
        self._save_state()

        # Sort indices
        sorted_indices = sorted(self.selected_masks)

        # Combine masks using logical OR
        combined_mask = np.zeros_like(self.masks[0], dtype=bool)
        combined_score = 0.0

        for idx in sorted_indices:
            combined_mask = np.logical_or(combined_mask, self.masks[idx])
            combined_score += self.scores[idx]

        # Average the scores
        combined_score /= len(sorted_indices)

        # Remove old masks (from end to start)
        for idx in sorted(sorted_indices, reverse=True):
            del self.masks[idx]
            del self.scores[idx]

        # Add combined mask at the position of the first selected mask
        insert_position = min(sorted_indices)
        self.masks.insert(insert_position, combined_mask)
        self.scores.insert(insert_position, combined_score)

        # Update colors
        self.colors = self._generate_colors(len(self.masks))

        # Clear selection and select the new combined mask
        self.selected_masks.clear()
        self.selected_masks.add(insert_position)

        # Update UI
        self.modified = True
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status(f"Combined {len(sorted_indices)} masks into mask #{insert_position}")

    def _save_state(self):
        """Save current state for undo"""
        # Deep copy the current state
        state = {
            'masks': [mask.copy() for mask in self.masks],
            'scores': self.scores.copy(),
            'selected': self.selected_masks.copy()
        }
        self.history.append(state)

        # Clear redo stack when new action is performed
        self.redo_stack.clear()

        # Limit history size to prevent memory issues
        if len(self.history) > 50:
            self.history.pop(0)

    def undo(self):
        """Undo last action"""
        if not self.history:
            self.update_status("Nothing to undo")
            return

        # Save current state to redo stack
        current_state = {
            'masks': [mask.copy() for mask in self.masks],
            'scores': self.scores.copy(),
            'selected': self.selected_masks.copy()
        }
        self.redo_stack.append(current_state)

        # Restore previous state
        state = self.history.pop()
        self.masks = [mask.copy() for mask in state['masks']]
        self.scores = state['scores'].copy()
        self.selected_masks = state['selected'].copy()

        # Update colors
        self.colors = self._generate_colors(len(self.masks))

        # Update UI
        self.modified = True
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status("Undo successful")

    def redo(self):
        """Redo last undone action"""
        if not self.redo_stack:
            self.update_status("Nothing to redo")
            return

        # Save current state to history
        self._save_state()

        # Restore redo state
        state = self.redo_stack.pop()
        self.masks = [mask.copy() for mask in state['masks']]
        self.scores = state['scores'].copy()
        self.selected_masks = state['selected'].copy()

        # Update colors
        self.colors = self._generate_colors(len(self.masks))

        # Update UI
        self.modified = True
        self.update_mask_list()
        self.update_details_panel()
        self.render_visualization()
        self.update_status("Redo successful")

    def save(self):
        """Save modifications back to the original files"""
        if not self.modified:
            messagebox.showinfo("No Changes", "No modifications to save.")
            return

        result = messagebox.askyesno("Save Changes",
                                     f"Save changes to:\n{self.masks_npz_path}\n{self.results_json_path}?")
        if not result:
            return

        self._save_files(self.masks_npz_path, self.results_json_path)

    def save_as(self):
        """Save modifications to new files"""
        # Ask for new .npz file path
        npz_path = filedialog.asksaveasfilename(
            title="Save masks as...",
            defaultextension=".npz",
            filetypes=[("NumPy compressed", "*.npz"), ("All files", "*.*")],
            initialfile=Path(self.masks_npz_path).name
        )

        if not npz_path:
            return

        # Automatically determine JSON path
        json_path = str(Path(npz_path).with_suffix('.json').with_name(
            Path(npz_path).stem.replace('_masks', '_results') + '.json'
        ))

        self._save_files(npz_path, json_path)

    def _save_files(self, npz_path: str, json_path: str):
        """Save masks and JSON to specified paths"""
        try:
            # 1. Save masks to .npz
            masks_array = np.array(self.masks)
            scores_array = np.array(self.scores)

            np.savez_compressed(
                npz_path,
                masks=masks_array,
                scores=scores_array,
                image_shape=self.image.shape,
                num_masks=len(self.masks)
            )

            # 2. Update and save JSON
            # Rebuild masks_info from current masks
            self.json_data['num_masks'] = len(self.masks)
            self.json_data['masks_info'] = []

            for i, (mask, score) in enumerate(zip(self.masks, self.scores)):
                area = np.sum(mask)
                bbox = self._get_mask_bbox(mask)

                mask_info = {
                    'id': i,
                    'score': float(score),
                    'area': int(area),
                    'bbox': [int(bbox[0]), int(bbox[1]), int(bbox[2]), int(bbox[3])]
                }

                self.json_data['masks_info'].append(mask_info)

            # Save JSON
            with open(json_path, 'w') as f:
                json.dump(self.json_data, f, indent=2)

            # Update paths if different
            self.masks_npz_path = npz_path
            self.results_json_path = json_path

            # Mark as not modified
            self.modified = False

            # Add note if masks were created from bboxes
            save_msg = f"Saved {len(self.masks)} masks to:\n{npz_path}\n{json_path}"
            if self.use_bbox_masks:
                save_msg += "\n\nNote: Original masks were rectangular (from bboxes).\nSaved masks will remain rectangular unless you combined them."

            messagebox.showinfo("Save Successful", save_msg)
            self.update_status(f"Saved {len(self.masks)} masks")

        except Exception as e:
            messagebox.showerror("Save Error", f"Error saving files:\n{str(e)}")
            self.update_status(f"Save failed: {str(e)}")

    def _get_mask_bbox(self, mask: np.ndarray) -> Tuple[int, int, int, int]:
        """Get bounding box of a mask"""
        if not np.any(mask):
            return (0, 0, 0, 0)

        rows = np.any(mask, axis=1)
        cols = np.any(mask, axis=0)

        y1, y2 = np.where(rows)[0][[0, -1]]
        x1, x2 = np.where(cols)[0][[0, -1]]

        return (x1, y1, x2 + 1, y2 + 1)

    def update_status(self, message: str):
        """Update status bar message"""
        self.status_bar.config(text=message)
        self.root.update_idletasks()

    def on_closing(self):
        """Handle window closing event"""
        if self.modified:
            result = messagebox.askyesnocancel(
                "Unsaved Changes",
                "You have unsaved changes. Do you want to save before exiting?"
            )

            if result is None:  # Cancel
                return
            elif result:  # Yes
                self.save()

        self.root.destroy()

    def run(self):
        """Run the GUI event loop"""
        self.root.protocol("WM_DELETE_WINDOW", self.on_closing)
        self.root.mainloop()


def main():
    parser = argparse.ArgumentParser(
        description='Interactive Mask Editor for SAM2 AMG Output',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  python interactive_mask_editor.py --results_json results/image_results.json

The script will automatically find the corresponding masks .npz file and image
based on the JSON file location and content.

Keyboard Shortcuts:
  E             - Edit selected mask (resize bounding box)
  N             - Create new mask (draw bounding box)
  Enter         - Apply current edit/creation
  Escape        - Cancel edit mode or clear selection
  Ctrl+Z        - Undo
  Ctrl+Y        - Redo
  Ctrl+S        - Save
  Delete        - Delete selected masks
        """
    )

    parser.add_argument('--results_json', type=str, required=True,
                       help='Path to the results JSON file from sam2_amg_inference.py')

    args = parser.parse_args()

    # Validate input
    if not os.path.exists(args.results_json):
        print(f"ERROR: JSON file not found: {args.results_json}")
        sys.exit(1)

    print("=" * 60)
    print("Interactive Mask Editor")
    print("=" * 60)
    print(f"JSON:        {args.results_json}")
    print("=" * 60)
    print("\nLoading data...")

    # Create and run editor
    try:
        editor = MaskEditor(results_json_path=args.results_json)

        print("=" * 60)
        print(f"Image:       {editor.image_path}")
        print(f"Masks:       {editor.masks_npz_path}")
        print(f"Total masks: {len(editor.masks)}")
        print("=" * 60)
        print("\nStarting interactive editor...")

        editor.run()

        print("\nEditor closed.")

    except Exception as e:
        print(f"\nERROR: {str(e)}")
        import traceback
        traceback.print_exc()
        sys.exit(1)


if __name__ == "__main__":
    main()
